/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.archerlights.control.forms;

import java.awt.Color;
import javax.swing.ImageIcon;
import org.archerlights.control.Counter;
import org.archerlights.control.Light;
import org.archerlights.control.TeamMode;

/**
 *
 * @author arogarth
 */
public class DesktopApp extends javax.swing.JFrame implements Counter.CounterListener {

    /**
     * Creates new form DesktopApp
     */
    public DesktopApp() {
        initComponents();
        Counter.getInstance().addCounterListerner(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lightRED = new javax.swing.JLabel();
        lightYELLOW = new javax.swing.JLabel();
        lightGREEN = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lightAB = new javax.swing.JLabel();
        lightCD = new javax.swing.JLabel();
        imageAcoustic = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnStart = new javax.swing.JButton();
        btnStopp = new javax.swing.JButton();
        btnSwitchGroup = new javax.swing.JButton();
        btnEmergenyStopp = new javax.swing.JButton();
        lblArcherLights = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(3, 1));

        lightRED.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/red_on.png"))); // NOI18N
        jPanel1.add(lightRED);

        lightYELLOW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/green_off.png"))); // NOI18N
        jPanel1.add(lightYELLOW);

        lightGREEN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yellow_off.png"))); // NOI18N
        jPanel1.add(lightGREEN);

        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        lightAB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ab_on.png"))); // NOI18N
        jPanel3.add(lightAB);

        lightCD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cd_off.png"))); // NOI18N
        jPanel3.add(lightCD);

        imageAcoustic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/acoustic_off.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imageAcoustic)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imageAcoustic))
        );

        btnStart.setFont(new java.awt.Font("DejaVu Sans", 1, 32)); // NOI18N
        btnStart.setText("START");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnStopp.setFont(new java.awt.Font("DejaVu Sans", 1, 32)); // NOI18N
        btnStopp.setText("STOPP");
        btnStopp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStoppActionPerformed(evt);
            }
        });

        btnSwitchGroup.setFont(new java.awt.Font("DejaVu Sans", 1, 32)); // NOI18N
        btnSwitchGroup.setText("AB/CD");
        btnSwitchGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSwitchGroupActionPerformed(evt);
            }
        });

        btnEmergenyStopp.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        btnEmergenyStopp.setText("<html>NOT<br/>STOPP</html>");
        btnEmergenyStopp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmergenyStoppActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnStopp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSwitchGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEmergenyStopp, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnStopp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSwitchGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(btnEmergenyStopp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblArcherLights.setFont(new java.awt.Font("DejaVu Sans", 1, 48)); // NOI18N
        lblArcherLights.setText("ArcherLights");

        lblTime.setFont(new java.awt.Font("DejaVu Sans", 1, 48)); // NOI18N
        lblTime.setText("00:00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTime))
                    .addComponent(lblArcherLights))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTime))
                        .addGap(166, 166, 166)
                        .addComponent(lblArcherLights))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStoppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStoppActionPerformed
        Counter.getInstance().stop();
    }//GEN-LAST:event_btnStoppActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        Counter.getInstance().start();
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnSwitchGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSwitchGroupActionPerformed
        Counter.getInstance().switchTeammode();
    }//GEN-LAST:event_btnSwitchGroupActionPerformed

    private void btnEmergenyStoppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmergenyStoppActionPerformed
        Counter.getInstance().emergencyStop();
    }//GEN-LAST:event_btnEmergenyStoppActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DesktopApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DesktopApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DesktopApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DesktopApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DesktopApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmergenyStopp;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStopp;
    private javax.swing.JButton btnSwitchGroup;
    private javax.swing.JLabel imageAcoustic;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblArcherLights;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lightAB;
    private javax.swing.JLabel lightCD;
    private javax.swing.JLabel lightGREEN;
    private javax.swing.JLabel lightRED;
    private javax.swing.JLabel lightYELLOW;
    // End of variables declaration//GEN-END:variables
        
    public void initNewRound() {
        //this.lghtAcoustic.setBackground(Color.gray);
    }
    
    @Override
    public void startWaiting() {
        this.setRed();
        this.startAcoustic(2);
    }

    @Override
    public void startShooting() {
        this.setGreen();
        this.startAcoustic(1);
    }

    @Override
    public void stopShooting() {
        this.setRed();
        this.startAcoustic(3);
    }
    
    @Override
    public void emergencyStop() {
        this.setRed();
        //this.lblTime.setText("0");
        this.startAcoustic(10);
    }

    @Override
    public void setTime(Integer time) {
        this.lblTime.setText(this.getTimeString(time));

        if (Counter.getInstance().isShooting()
         && !Counter.getInstance().isWaiting()
         && time <= Counter.getInstance().getCountDownTime()) {
            this.setYellow();
        }
    }

    @Override
    public void setTeam(TeamMode mode, Integer current, Integer max) {
        
        if(mode.equals(TeamMode.AB)) {
            this.setAB();
        } else {
            this.setCD();
        }
        
        String format = "%s/%s";
        if(max == null) format = "%s";
        //this.lblRound.setText(String.format(format,  current, max));
    }

    private String getTimeString(int totalSeconds) {
        int hours = Math.floorDiv( totalSeconds, 60 );
        int seconds = Math.floorMod( totalSeconds, 60 );
        
        return String.format("%02d:%02d", hours, seconds);
        
    }
    
    private void setRed() {
        lightGREEN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/green_off.png")));
        lightYELLOW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yellow_off.png")));
        lightRED.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/red_on.png")));
    }
    
    private void setYellow() {
        lightGREEN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/green_off.png")));
        lightYELLOW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yellow_on.png")));
        lightRED.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/red_off.png")));
    }
    
    private void setGreen() {
        lightGREEN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/green_on.png")));
        lightYELLOW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yellow_off.png")));
        lightRED.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/red_off.png")));
    }
    
    private void setAB() {
        lightAB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ab_on.png")));
        lightCD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cd_off.png")));
    }
    
    private void setCD() {
        lightAB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ab_off.png")));
        lightCD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cd_on.png")));
    }
    
    private void startAcoustic(int times) {
        try {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        for(int i=0; i < times; i++) {
                            imageAcoustic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/acoustic_on.png")));

                            Thread.sleep(500l);
                            imageAcoustic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/acoustic_off.png")));
                            Thread.sleep(500l);
                        }
                    } catch (Exception e) {}
                }
            }).start();
        } catch (Exception e) {}
        
        //this.lghtAcoustic.setBackground(Color.gray);
    }
}
