/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.archerlights.control.forms;

import java.awt.Color;
import java.util.Timer;
import org.archerlights.control.Counter;
import org.archerlights.control.TeamMode;

/**
 *
 * @author arogarth
 */
public class MainControl extends JFullscreenFrame implements Counter.CounterListener {

    /**
     * Creates new form MainControl
     */
    public MainControl(JFullscreenFrame parent) {
        super(parent);

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStart = new javax.swing.JButton();
        btnEnd = new javax.swing.JButton();
        btnGroup = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        lblTime = new javax.swing.JLabel();
        lghtSignal = new javax.swing.JPanel();
        lghtAcoustic = new javax.swing.JPanel();
        lblGroup = new javax.swing.JLabel();
        lblRound = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(320, 240));
        setMinimumSize(new java.awt.Dimension(320, 240));
        setPreferredSize(new java.awt.Dimension(320, 240));
        setResizable(false);
        setSize(new java.awt.Dimension(320, 240));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnStart.setBackground(new java.awt.Color(171, 171, 171));
        btnStart.setText("START");
        btnStart.setAlignmentY(0.0F);
        btnStart.setMargin(new java.awt.Insets(0, -10, 0, 0));
        btnStart.setMaximumSize(new java.awt.Dimension(65, 65));
        btnStart.setMinimumSize(new java.awt.Dimension(65, 65));
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        getContentPane().add(btnStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 65, 65));

        btnEnd.setBackground(new java.awt.Color(171, 171, 171));
        btnEnd.setText("ENDE");
        btnEnd.setMargin(new java.awt.Insets(0, -10, 0, 0));
        btnEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEndActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 65, 65));

        btnGroup.setBackground(new java.awt.Color(171, 171, 171));
        btnGroup.setText("AB/CD");
        btnGroup.setMargin(new java.awt.Insets(0, -10, 0, 0));
        btnGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGroupActionPerformed(evt);
            }
        });
        getContentPane().add(btnGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 65, 65));

        btnStop.setBackground(new java.awt.Color(255, 3, 0));
        btnStop.setForeground(new java.awt.Color(1, 1, 1));
        btnStop.setText("<html>NOT<br/>STOPP</html>");
        btnStop.setMargin(new java.awt.Insets(0, -10, 0, 0));
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });
        getContentPane().add(btnStop, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 65, 65));

        lblTime.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTime.setText("04:00");
        lblTime.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 116, 40));

        lghtSignal.setBackground(new java.awt.Color(255, 253, 0));
        lghtSignal.setMinimumSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout lghtSignalLayout = new javax.swing.GroupLayout(lghtSignal);
        lghtSignal.setLayout(lghtSignalLayout);
        lghtSignalLayout.setHorizontalGroup(
            lghtSignalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        lghtSignalLayout.setVerticalGroup(
            lghtSignalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        getContentPane().add(lghtSignal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, -1));

        lghtAcoustic.setBackground(new java.awt.Color(0, 2, 255));

        javax.swing.GroupLayout lghtAcousticLayout = new javax.swing.GroupLayout(lghtAcoustic);
        lghtAcoustic.setLayout(lghtAcousticLayout);
        lghtAcousticLayout.setHorizontalGroup(
            lghtAcousticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        lghtAcousticLayout.setVerticalGroup(
            lghtAcousticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(lghtAcoustic, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, 64));

        lblGroup.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblGroup.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGroup.setText("AB");
        getContentPane().add(lblGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 70, -1));

        lblRound.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblRound.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRound.setText("01/10");
        getContentPane().add(lblRound, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        Counter.getInstance().emergencyStop();
    }//GEN-LAST:event_btnStopActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed

        Counter.getInstance().start();
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndActionPerformed

        Counter.getInstance().stop();
    }//GEN-LAST:event_btnEndActionPerformed

    private void btnGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGroupActionPerformed
        Counter.getInstance().switchTeammode();
    }//GEN-LAST:event_btnGroupActionPerformed
    
    private void blinkLight(Integer times) {
        try {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        for(int i=0; i < times; i++) {
                            lghtAcoustic.setBackground(Color.blue);

                            Thread.sleep(500l);
                            lghtAcoustic.setBackground(Color.gray);
                            Thread.sleep(500l);
                        }
                    } catch (Exception e) {}
                }
            }).start();
        } catch (Exception e) {}
        
        this.lghtAcoustic.setBackground(Color.gray);
    }
        
    public void initNewRound() {
        this.lghtAcoustic.setBackground(Color.gray);
    }

    @Override
    public void startWaiting() {
        this.lghtSignal.setBackground(Color.yellow);
        this.blinkLight(2);
    }

    @Override
    public void startShooting() {
        this.lghtSignal.setBackground(Color.green);
        this.blinkLight(1);
    }

    @Override
    public void stopShooting() {
        this.lghtSignal.setBackground(Color.red);
        this.blinkLight(3);
    }
    
    @Override
    public void emergencyStop() {
        this.lghtSignal.setBackground(Color.red);
        this.lblTime.setText("0");
        this.blinkLight(10);
    }

    @Override
    public void setTime(Integer time) {
        this.lblTime.setText(time.toString());

        if (!Counter.getInstance().isWaiting()) {
            if (time == 0) {
                this.lghtSignal.setBackground(Color.red);
            } else if (time <= Counter.getInstance().getCountDownTime()) {
                this.lghtSignal.setBackground(Color.yellow);
            }
        }
    }

    @Override
    public void setTeam(TeamMode mode, Integer current, Integer max) {
        
        this.lblGroup.setText(mode.name());
        
        String format = "%s/%s";
        if(max == null) format = "%s";
        this.lblRound.setText(String.format(format,  current, max));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnd;
    private javax.swing.JButton btnGroup;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel lblGroup;
    private javax.swing.JLabel lblRound;
    private javax.swing.JLabel lblTime;
    private javax.swing.JPanel lghtAcoustic;
    private javax.swing.JPanel lghtSignal;
    // End of variables declaration//GEN-END:variables

    
}
